DROP PROCEDURE IF EXISTS `borhandw_ds`.`add_file_partition`;
DROP PROCEDURE IF EXISTS `borhandw_ds`.`add_ods_partition`;
DROP PROCEDURE IF EXISTS `borhandw_ds`.`drop_ods_partition`;
DROP PROCEDURE IF EXISTS `borhandw_ds`.`drop_file_partition`;
DROP PROCEDURE IF EXISTS `borhandw_ds`.`empty_file_partition`;
DROP PROCEDURE IF EXISTS `borhandw_ds`.`empty_file_partition`;
DROP PROCEDURE IF EXISTS `borhandw_ds`.`empty_ods_partition`;
DROP PROCEDURE IF EXISTS `borhandw_ds`.`transfer_file_partition`;
DROP PROCEDURE IF EXISTS `borhandw_ds`.`transfer_ods_partition`;
