RENAME TABLE borhandw.dwh_dim_partner_sub_activity TO borhandw.dwh_dim_partner_sub_activity_20110607;
RENAME TABLE borhandw.dwh_dim_partner_activity TO borhandw.dwh_dim_partner_activity_20110607;
RENAME TABLE borhandw.dwh_fact_partner_activities TO borhandw.dwh_fact_partner_activities_20110607;
RENAME TABLE borhandw_bisources.bisources_partner_activity TO borhandw_bisources.bisources_partner_activity_20110607;
RENAME TABLE borhandw_bisources.bisources_partner_sub_activity TO borhandw_bisources.bisources_partner_sub_activity_20110607;

